services:
  ollama:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    container_name: ollama_svc
    volumes:
      - ollama_data:/root/.ollama

  chroma:
    image: chromadb/chroma
    container_name: chroma_svc
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma

  llm-service:
    build: .
    image: kwonsoonmin/llm-service:0.1
    container_name: llm-svc
    depends_on:
      - ollama
      - chroma
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - CHROMA_HOST=chroma
      - SPRING_SERVER_URL=http://spring-app:8080
      - VECTOR_DB_HOST=chroma
      - VECTOR_DB_PORT=8001
    entrypoint: ["/app/entrypoint.sh"]

volumes:
  ollama_data:
  chroma_data:
