name: Dev Build and Deploy

on:
  push:
    branches:
      - dev

env:
  DOCKER_IMAGE: llm-service
  DOCKER_TAG: 0.1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Compose services
        run: docker-compose build

      - name: Push Docker Compose services
        run: docker-compose push