name: Build and Push, and Deploy LLM Service

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  DOCKER_IMAGE: llm-service
  DOCKER_TAG: 0.3
  PROJECT_DIRECTORY: llm-svc

jobs:
  Docker:
    runs-on: ubuntu-latest

    steps:
      # 소스 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v4

      # Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./llm-service.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~
            if [ ! -d "${{ env.PROJECT_DIRECTORY }}" ]; then
              git clone https://github.com/rookies-team1/langchain.git ${{ env.PROJECT_DIRECTORY }}
            fi
            cd ${{ env.PROJECT_DIRECTORY }}
            git pull origin main
                      
            echo "OLLAMA_BASE_URL=${{ secrets.OLLAMA_BASE_URL }}" > .env
            echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env
            echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}" >> .env
            echo "VECTOR_DB_PORT=${{ secrets.VECTOR_DB_PORT }}" >> .env
            echo "VECTOR_DB_HOST=${{ secrets.VECTOR_DB_HOST }}" >> .env
            echo "LANGSMITH_ENDPOINT=${{ secrets.LANGSMITH_ENDPOINT }}" >> .env
            echo "LANGSMITH_API_KEY=${{ secrets.LANGSMITH_API_KEY }}" >> .env

            docker-compose pull

            docker-compose down

            docker-compose up -d

      # 빌드 결과 출력
      - name: Image digest
        run: echo "Image pushed successfully to ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}"
